# Generated by Django 5.2.5 on 2025-08-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Persona',
        ),
    ]
