# Generated by Django 5.2.5 on 2025-08-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculasApp', '0002_alter_person_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='ingresa tu nombre', max_length=50)),
                ('last_name', models.CharField(help_text='ingresa tu apellido', max_length=50)),
                ('age', models.IntegerField(help_text='ingresa tu edad')),
                ('enrollment_date', models.DateField(help_text='ingresa la fecha de inscripción')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiantes',
            },
        ),
    ]
