# Generated by Django 5.1.5 on 2025-08-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='indica tus 2 nombres', max_length=50)),
                ('last_name', models.CharField(help_text='indica tus 2 apellidos', max_length=50)),
                ('age', models.IntegerField(help_text='pon tu edad')),
            ],
        ),
    ]
